# Generated by Django 4.1.4 on 2023-01-24 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega3', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospedaje',
            old_name='Personas',
            new_name='Cantidad_Personas',
        ),
        migrations.RenameField(
            model_name='hospedaje',
            old_name='Hoteles',
            new_name='Tipo_Hopedaje',
        ),
    ]
