# Generated by Django 4.1.4 on 2023-01-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega3', '0002_rename_personas_hospedaje_cantidad_personas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opiniones_Viajeros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Nacionalidad', models.CharField(max_length=40)),
                ('Opiniones', models.CharField(max_length=60)),
            ],
        ),
        migrations.RenameField(
            model_name='hospedaje',
            old_name='Tipo_Hopedaje',
            new_name='Tipo_Hospedaje',
        ),
    ]
